version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=crane_k1Ck
      - POSTGRES_DB=fastapi
      - POSTGRES_USER=yash33
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
